### ISSUE TITLE
Command Line access

### ISSUE THREAD

**Issue by BeccaMallett** [Irwin-Blair/Group-F#10]
Need to make sure everyone can access the module directly and in the command line

**Comment by ciarms** [comment]
Becca what do you mean by accessing the module directly?

**Comment by BeccaMallett** [comment]
On the moodle mark scheme it is talking about the user being able to put our package into code and use it, like how we use NUMPY. Then they also need to be able to read it  and install it from the command line e.g. linux

**Comment by BeccaMallett** [comment]
This has been done in the Potential_Function.py code

**Comment by BeccaMallett** [comment]
I am going to close this issue

**Comment by Irwin-Blair** [comment]
The requirements are below
tkinter
matplotlib
numpy
PIL
itertools
findiff
scipy
