### ISSUE TITLE
Writing help on how to use the software

### ISSUE THREAD

**Issue by BeccaMallett** [Irwin-Blair/Group-F#12]
Someone needs to write how to use the software once developed

**Comment by ciarms** [comment]
I've started a README file for our software, it will need adding to as the software is further developed.

**Comment by ciarms** [comment]
When @Irwin-Blair and @Iarla-Boyce have merged their functions I will update the README

**Comment by BeccaMallett** [comment]
Send it to me and I will add it to the package once completed

**Comment by BeccaMallett** [comment]
I am going to close this as we have a separate branch relating to this
