### ISSUE TITLE
Differentiation of x and t

### ISSUE THREAD

**Issue by BeccaMallett** [Irwin-Blair/Group-F#17]
Two differentiation functions need to be developed to use in the Schrodinger equation.

**Comment by BeccaMallett** [comment]
Adding Iarla, as FinDiff doesn't work on my laptop, I created a basic code and Iarla is building on that, then I will write documentation

**Comment by BeccaMallett** [comment]
We need to make an array of x and y points so the FinDiff function prints values rather than positions

**Comment by BeccaMallett** [comment]
E.g. N = number of points and x_array = np.linspace(xmin,xmax,N)

**Comment by BeccaMallett** [comment]
For first diff of time
dt = t[1] - t[0]
FinDiff(0,dt,1)

For second diff of x (position)
dx = x[1] - x[0]
FinDif(0,dx,2)

**Comment by Iarla-Boyce** [comment]
Form matrix using the arrays with N terms to make it suitable for user input.

**Comment by BeccaMallett** [comment]
Are you doing two functions? One for t and one for x?

**Comment by Iarla-Boyce** [comment]
Considering an if-else loop for the order of DE, not sure if this is correct. Will test and update.

**Comment by Iarla-Boyce** [comment]
Have created code with a variable V(x) input using the function User_Defined_Potential created by Irwin

**Comment by Iarla-Boyce** [comment]
Also, allow user input on the placement of the wave function on the plot using the function KindInput created by Irwin.
