### ISSUE TITLE
User imput potential function

### ISSUE THREAD

**Issue by BeccaMallett** [Irwin-Blair/Group-F#18]
Need the user to be able to input a function for the potential energy

**Comment by ciarms** [comment]
is calling it Potential Function.py (with the space in it) going to cause problems?

**Comment by BeccaMallett** [comment]
It might be safer to call it Potential_Function.py?

**Comment by Irwin-Blair** [comment]
Done for now, with some possible improvements left at end, in a comment.

**Comment by BeccaMallett** [comment]
OK if you are done, I will start to write some documentation on it
