### ISSUE TITLE
Merging seperate code 

### ISSUE THREAD

**Issue by Iarla-Boyce** [Irwin-Blair/Group-F#29]
Irwin and I will attempt to merge our code into one python file.

**Comment by Iarla-Boyce** [comment]
My python file, V_x-Function.py, has been added to the main branch of the git

**Comment by BeccaMallett** [comment]
Have you guys been able to merge your code ok?

**Comment by Iarla-Boyce** [comment]
The code is merged and working with user inputs for both Schrodinger simulation and potential function. Currently working out formatting and GUI

**Comment by BeccaMallett** [comment]
Great!

**Comment by Iarla-Boyce** [comment]
The code has been merged and is working with a finished GUI. Closing this issue now.
