### ISSUE TITLE
How does Expression class work? 

### ISSUE THREAD

**Issue by Irwin-Blair** [Irwin-Blair/Group-F#38]
Found in branch 25 - taking user input. Can you add a quick example of how to use it to take a function?

**Comment by aproctorlowe** [comment]
I realise now that I haven't structured the class to interact externally, yet. I have changed this locally, but I appear to be unable to commit the update to the main directory. I will try to push changes for this tomorrow, as I need to leave now. 

As an overview of what will happen, you will call the 'getFunction()' method - passing in user input - and receive an expression class.

Use this expression class to evaluate the function with the 'evaluate()' method - passing in values for all given variables. If you call 'getVariables()' on an expression, it will return a list of all variables needed to evaluate it, so you know which variables you need to ask the user to specify.

Additionally, the expressions class has a 'printConfirmation()' method. This will return the inferred function. Prompt the user to confirm that this matches their expectations or allow them to alter their input if it doesn't.

Importantly, make sure that any input passed to the expressions class is a valid string.

**Comment by BeccaMallett** [comment]
@aproctorlowe I have looked at your pull request and commented on it there, but your issue seems to be with a deleted potential function file, which is why it is not merging, I see there is no branch for this issue, how did you make your changes? Please dont try and make changes on the main directly and instead make a branch attached to an issue please

**Comment by aproctorlowe** [comment]
I included a short example of how to use the built-in functions at the bottom of the expressions class. Note that decimal values will break the code, but fractions will work as intended, so it may be a good idea to prompt users to input fractions rather than decimals.

**Comment by aproctorlowe** [comment]
And also, where I pass in the array ["x", "a"] to the evaluate method, make sure this array contains each of the user specified variables and values for them, otherwise the code also breaks.
