### ISSUE TITLE
Requirements problem in test

### ISSUE THREAD

**Issue by ciarms** [Irwin-Blair/Group-F#39]
I'm trying to make sure the installation instructions in the README work. I got as far as installing requirements.txt and got:
ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter

I'm assuming this came from somewhere to be used in the code, so it does exist. Any ideas @Irwin-Blair ?

**Comment by ciarms** [comment]
apparently pip doesn't like tkinter. I've used `pip install Tk interface` and tried moving onto `pip install -r GUI.py` and now the error is:
ERROR: Invalid requirement: 'import tkinter as tk' (from line 1 of GUI.py)

this isn't very user friendly, I'm going to try and work out how the GUI can be opened without this problem

**Comment by ciarms** [comment]
I've not really been able to get anywhere with this, anyone have any ideas?

**Comment by Irwin-Blair** [comment]
try pip install tk

**Comment by ciarms** [comment]
pip install tk resulted in requirement already satisfied.

I think the problem is the import tkinter as tk inside GUI.py

**Comment by BeccaMallett** [comment]
I think this problem has been resolved @ciarms so can you close this issue please if it has been.
