### ISSUE TITLE
Code, and code folders confusing

### ISSUE THREAD

**Issue by BeccaMallett** [Irwin-Blair/Group-F#42]
Iarla is making a Schodingers folder so we can delete these two

**Comment by BeccaMallett** [comment]
The two folders need to be deleted now and everyone needs to pull the main

**Comment by rfwade02** [comment]
Iarla has created a Schrodinger folder, copy of 'code'
'code' folder has been deleted
'Code' folder left for the moment since it contains the Potential_Function.py with @BeccaMallett 's docstring.
Leaving issue open for now, preferably until everyone's pulled updated main.

**Comment by BeccaMallett** [comment]
I have updated mine, thank you @rfwade02 for summarising this issue

**Comment by BeccaMallett** [comment]
I am now going to close this issue
