### ISSUE TITLE
Checking everyone can push files to the Github

### ISSUE THREAD

**Issue by Irwin-Blair** [Irwin-Blair/Group-F#5]
Hey all, can you all clone the github repo with this command: git clone https://github.com/Irwin-Blair/Group-F

Once you've done that, add a new text file to the folder, with your name in it please

**Comment by BeccaMallett** [comment]
I have cloned Group F, but having an issue pushing due to password errors, happening to iarla too

**Comment by ciarms** [comment]
> I have cloned Group F, but having an issue pushing due to password errors, happening to iarla too

same

**Comment by BeccaMallett** [comment]
Everyone can do this so i will close this issue :)
